name: CD

on:
  push:
    branches: [main]

jobs:
  publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: backend
          target: production
          push: true
          tags: |
            ghcr.io/harrysad/mern-crm-backend:latest
            ghcr.io/harrysad/mern-crm-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: frontend
          target: production
          push: true
          tags: |
            ghcr.io/harrysad/mern-crm-frontend:latest
            ghcr.io/harrysad/mern-crm-frontend:${{ github.sha }}
